enum PostScope {
  REGION_ONLY = "REGION_ONLY",
  PROVINCE_ONLY = "PROVINCE_ONLY",
  MUNICIPALITY_ONLY = "MUNICIPALITY_ONLY",
  REGION_AND_PROVINCE = "REGION_AND_PROVINCE",
  REGION_AND_MUNICIPALITIES = "REGION_AND_MUNICIPALITIES",
  PROVINCE_AND_MUNICIPALITIES = "PROVINCE_AND_MUNICIPALITIES",
  REGION_PROVINCES_AND_MUNICIPALITIES = "REGION_PROVINCES_AND_MUNICIPALITIES",
  MUNICIPALITIES_SELECTED = "MUNICIPALITIES_SELECTED",
  ALL_MUNICIPALITIES = "ALL_MUNICIPALITIES",
  EVERYWHERE = "EVERYWHERE",
}

export default PostScope;
